referral_system/referral_system/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('api/', include('users.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

referral_system/users/urls.py
from django.urls import path

from .views import (
    PhoneNumberView,
    CodeVerificationView,
    UserProfileView
)

app_name = 'users'

urlpatterns = [
    path('auth/phone/', PhoneNumberView.as_view(), name='phone_auth'),
    path('auth/code/<str:phone_number>/', CodeVerificationView.as_view(), name='code_verification'),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
]

referral_system/users/models.py
import random
import string
from django.db import models


class User(models.Model):
    phone_number = models.CharField(max_length=15, unique=True)
    invite_code = models.CharField(max_length=6, unique=True, null=True, blank=True)
    activated_invite_code = models.BooleanField(default=False)
    inviter = models.ForeignKey('User', null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.phone_number


class Referral(models.Model):
    user = models.ForeignKey(User, related_name='referrals', on_delete=models.CASCADE)
    referred_user = models.ForeignKey(User, related_name='referred_by', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.phone_number} referred {self.referred_user.phone_number}"

referral_system/users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from rest_framework import generics, status
from rest_framework.generics import GenericAPIView
from rest_framework.response import Response
from rest_framework.views import APIView
from .models import User, Referral
from .serializers import UserSerializer
import random
import string
import time


def generate_invite_code():
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))


class PhoneNumberView(GenericAPIView):
    serializer_class = UserSerializer

    def get(self, request):
        return render(request, 'users/login.html')

    def post(self, request):
        phone_number = request.data.get('phone_number')
        user, created = User.objects.get_or_create(phone_number=phone_number)
        if created:
            # Генерация инвайт-кода
            user.invite_code = generate_invite_code()
            user.save()
            # Имитация задержки
            time.sleep(2)
            return redirect(reverse('users:code_verification', args=[phone_number]))
        if user.activated_invite_code is False:
            return redirect(reverse('users:code_verification', args=[phone_number]))
        else:
            return redirect(reverse('users:user_profile', args=[user.id]))


class CodeVerificationView(GenericAPIView):
    serializer_class = UserSerializer

    def get(self, request, phone_number):
        return render(request, 'users/confirm_code.html', {'phone_number': phone_number})

    def post(self, request, *args, **kwargs):
        phone_number = request.data.get('phone_number')
        code = request.data.get('code')

        try:
            user = User.objects.get(phone_number=phone_number)
            # Проверка кода подтверждения. Здесь предполагаем, что confirmation_code - это тот код, который нужно ввести
            if user.invite_code == code:
                user.activated_invite_code = True
                user.save()
                # Успешная проверка кода, можно перенаправить на профиль пользователя
                return redirect(reverse('users:user_profile', args=[user.id]))
            else:
                # Код неверный, обработайте ошибку
                return render(request, 'users/confirm_code.html', {
                    'phone_number': phone_number,
                    'error': 'Неверный код. Попробуйте еще раз.'
                })
        except User.DoesNotExist:
            return render(request, 'users/confirm_code.html', {
                'phone_number': phone_number,
                'error': 'Пользователь не найден.'
            })


class UserProfileView(GenericAPIView):
    serializer_class = UserSerializer

    def get(self, request, pk):
        user = User.objects.get(pk=pk)
        referrals = Referral.objects.filter(user=user)
        return render(request, 'users/profile.html', {'user': user, 'referrals': referrals}, status=status.HTTP_200_OK)

    def post(self, request, pk):
        user = User.objects.get(pk=pk)
        invite_code = request.data.get('invite_code')
        user.invite_code = invite_code
        user.save()
        return redirect(reverse('users:user_profile', args=[user.id]))

referral_system/users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
          Base Title
        {% endblock %}
    </title>
</head>
<body>
{% block body %}
  Base body
{% endblock %}

<div>
    {% now 'H:i' %}
</div>
<div>
    {% now 'l' as current_weekday %}
    Today is {{ current_weekday }}
</div>
</body>
</html>

referral_system/users/templates/users/confirm_code.html
{% extends 'users/base.html' %}

{% block title %}
    Подтверждение кода
{% endblock %}

{% block body %}
    <h1>Подтверждение кода</h1>
    <form action="{% url 'users:code_verification' phone_number=phone_number %}" method="post">
        {% csrf_token %}
        <label for="code">Введите код, отправленный на ваш номер телефона: {{ phone_number }}</label>
        <a href="{% url 'users:phone_auth' %}">Изменить номер телефона</a>
        <input type="text" id="code" name="code" required>
        <input type="hidden" name="phone_number" value="{{ phone_number }}">
        <button type="submit">Подтвердить код</button>
    </form>
{% endblock %}

referral_system/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block title %}
    Авторизация
{% endblock %}

{% block body %}
    <h1>Авторизация</h1>
    <form method="POST" action="{% url 'users:phone_auth' %}">
        {% csrf_token %}
        <label for="phone_number">Телефон:</label>
        <input type="text" name="phone_number" required>
        <button type="submit">Отправить код</button>
    </form>
{% endblock %}

referral_system/users/templates/users/profile.html
{% extends 'users/base.html' %}

{% block title %}
    Профиль пользователя
{% endblock %}

{% block body %}
<h1>Профиль пользователя</h1>
<p>Телефон: {{ user.phone_number }}</p>

<h2>Активированные коды:</h2>
<form method="POST">
    {% csrf_token %}
    <input type="text" name="invite_code" placeholder="Введите инвайт-код" required>
    <button type="submit">Активировать код</button>
</form>

<h2>Пользователи, которые активировали свой код:</h2>
<ul>
    {% for referral in referrals %}
        <li>{{ referral.referred_user }}</li>
    {% empty %}
        <li>Нет активированных пользователей.</li>
    {% endfor %}
</ul>
{% endblock %}